# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5b4246331cc597236591f0bc3f6b212dd58f8083634f3a3f75aea9f54550903220ff79503ea004c6a7d19bfceec5742350e853427ac6cce37137b3417e4f92c4

test:
  secret_key_base: 03bf1fab6d4af99071ed6fc8dc35cd42df17b068e742f8502c6880376eb8509adbb114dc9273d8839218d535e56c7ce4a3b2d6d884d336a6275ac4ec39bc8c52

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
